### Ollama Generate Test
POST http://localhost:11434/api/generate
Content-Type: application/json

{
    "model":"llama3.2:3b",
    "prompt" : "사용자 사용자아시아 국가 5개만 나열해봐, 단 5문장으로 나누어서 대답해",
    "stream": true
}


### /api/chat 엔드포인트 사용 
### 이 엔드포인트의 장점 
### 1) 대화 맥락 관리하기 좋다 
### 2) 표준 규격 : Open AI 의 api규격과 동일하여, 나중에 GPT, Claude 등 다른 모델로 교체할때 코드 수정이 거의없음
### 3) 역할 분담: system(역할-페르소나), user(질문자), assistant(답변자인ai)
POST http://localhost:11434/api/chat
Content-Type: application/json

{
    "model": "llama3.2:3b",
    "messages": [
        {
            "role":"user",
            "content":"안녕 반갑다"
        }
    ],
    "stream":true
}